theme: jekyll-theme-minimal
title: Alex dos Reis de Souza, PhD
description: Research Engineer
logo: https://github.com/reis-alex/reis-alex.github.io/blob/main/images/Alex.png?raw=true
show_downloads: false
