theme: jekyll-theme-minimal
title: Alex dos Reis de Souza
description: Software Engineer at Intel
logo: https://github.com/reis-alex/reis-alex.github.io/blob/main/images/Alex.png
show_downloads: false
